<?php
namespace App\Http\Requests\News;

use Illuminate\Foundation\Http\FormRequest;

class CreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules(): array
    {
        return [
            'category_id' => ['required', 'integer'],
            'source_id' => ['required', 'integer'],
            'status' => ['required', 'string'],
            'title' => ['required', 'string', 'min:5', 'max:55'],
            'author' => ['required', 'string', 'min:2', 'max:55'],
            'image' => ['nullable', 'file', 'image', 'mimes:jpg, png'],
            'description' => ['nullable', 'string', 'max:1000']
        ];
    }

    public function messages(): array
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    public function attributes(): array
    {
        return [
            'title' => 'заголовок',
            'author' => 'автор'
        ];
    }
}
